### ISSUE TITLE
Sign and verify signature test cases needed

### ISSUE THREAD

**Issue by dcb9** [binance/binance-pay-connector-python#3]
Thanks for the repo, it's helpful. I'm integrating Binance Pay to my project while not having the api key and secret.
Signing and verifying are the most important two steps of the protocol. For me test case for them is required. Further more everyone could develop a new Binance Pay client with the same test cases. If all tests are passed, developer will be confident about their implementation.

**Comment by 2pd** [comment]
- test cases are included, please find the test folder in the repo.
- test cases won't help to reduce the concern of using the library if you're talking about passing api key to the code.   That's why the library is open-sourced.  You can review every line of the code, every commit. It has only one dependency `requests`, which is also an open-source library.
- If the signature is not working, please let us know.
